name: Run Workday Scraper

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 0 * * 5,6,0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-for-daily-email:
    if: "!contains(github.event.schedule, '5,6,0')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # chris
    # - name: Run Chris
    #   run: python -m workday_scraper -f chris.txt -e ${{ secrets.EMAIL_SENDER }} -pw '${{ secrets.EMAIL_PASSWORD }}' -r ${{ secrets.EMAIL_TEST_RECIPIENT }} -nj
    # - name: Rename Chris
    #   run: mv rss.xml rss-chris.xml
      # umair
    - name: Run Umair
      run: python -m workday_scraper -f umair.txt -e ${{ secrets.EMAIL_SENDER }} -pw '${{ secrets.EMAIL_PASSWORD }}' -r ${{ secrets.EMAIL_UMAIR }} -nj
    - name: Rename Umair
      run: mv rss.xml rss-umair.xml
      # ahmed
    # - name: Run Ahmed
    #   run: python -m workday_scraper -f umair.txt -e ${{ secrets.EMAIL_SENDER }} -pw '${{ secrets.EMAIL_PASSWORD }}' -r ${{ secrets.EMAIL_AHMED }} -nj
    # - name: Rename Ahmed
    #   run: mv rss.xml rss-ahmed.xml
      # alex
      # - name: Run Alex
      # run: python -m workday_scraper -f alex.txt -e ${{ secrets.EMAIL_SENDER }} -pw '${{ secrets.EMAIL_PASSWORD }}' -r ${{ secrets.EMAIL_ALEX }} -nj
      # - name: Rename Alex
      # run: mv rss.xml rss-alex.xml
      # brennan
    - name: Run Brennan
      run: python -m workday_scraper -f brennan.txt -e ${{ secrets.EMAIL_SENDER }} -pw '${{ secrets.EMAIL_PASSWORD }}' -r ${{ secrets.EMAIL_BRENNAN }} -nj
    - name: Rename Brennan
      run: mv rss.xml rss-brennan.xml
      # jeff
    - name: Run Jeff
      run: python -m workday_scraper -f jeff.txt -e ${{ secrets.EMAIL_SENDER }} -pw '${{ secrets.EMAIL_PASSWORD }}' -r ${{ secrets.EMAIL_JEFFREY }} -nj
    - name: Rename Jeff
      run: mv rss.xml rss-jeff.xml
    - name: RSS folder
      run: |
        mkdir rss
        mv rss-* rss
    - uses: actions/upload-artifact@v4
      with:
        path: rss
    - name: RSS branch
      run: |
        git checkout --orphan rss
        git rm -rf .
    - uses: actions/download-artifact@v4
    - name: Push to rss
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email ${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com
        git add rss/*
        git commit -m "Run Workday Scraper"
        git push --set-upstream origin rss --force

  run-for-weekend-email:
    if: "contains(github.event.schedule, '5,6,0')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # seamus
    - name: Run Seamus
      run: python -m workday_scraper -f seamus.txt -e ${{ secrets.EMAIL_SENDER }} -pw '${{ secrets.EMAIL_PASSWORD }}' -r ${{ secrets.EMAIL_SEAMUS }} -nj
    - name: Rename Seamus
      run: mv rss.xml rss-seamus.xml
    - name: RSS folder
      run: |
        mkdir rss
        mv rss-* rss
    - uses: actions/upload-artifact@v4
      with:
        path: rss
    - name: RSS branch
      run: |
        git checkout --orphan rss
        git rm -rf .
    - uses: actions/download-artifact@v4
    - name: Push to rss
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email ${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com
        git add rss/*
        git commit -m "Run Workday Scraper"
        git push --set-upstream origin rss --force
